routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductsController;
use App\Http\Controllers\StocksController;
use App\Http\Controllers\SalesController;
use App\Http\Controllers\FuelPumpsController;
use App\Http\Controllers\FuelPumpReadingsController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CustomersController;
use App\Http\Controllers\DebtsController;
use App\Http\Controllers\DebtPaymentsController;
use App\Http\Controllers\ExpensesController;
use App\Models\Sale;
use App\Models\Stock;
use App\Models\Product;
use App\Models\FuelPump;
use App\Models\User;
use App\Models\FuelPumpReading;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/business_performance', [App\Http\Controllers\HomeController::class, 'businessPerfomance']);
Route::get('/products_performance', [App\Http\Controllers\HomeController::class, 'productsPerfomance']);
Route::resource('products', ProductsController::class)->middleware('auth');
Route::resource('customers', CustomersController::class)->middleware('auth');
Route::resource('debts', DebtsController::class)->middleware('auth');
Route::resource('stocks', StocksController::class)->middleware('auth');
Route::resource('sales', SalesController::class)->middleware('auth');
Route::resource('fuel_pumps', FuelPumpsController::class)->middleware('auth');
Route::get('fuel_pump/{pump_id}/calibrate', [App\Http\Controllers\FuelPumpsController::class, 'calibratePump'])->middleware('auth');
Route::post('fuel_pump/{pump_id}/calibrate', [App\Http\Controllers\FuelPumpsController::class, 'calibratePumpUpdate'])->middleware('auth');
Route::resource('fuel_pumps_readings', FuelPumpReadingsController::class)->middleware('auth');
Route::get('fuel_pumps_reading/{reading_id}/delete', [App\Http\Controllers\FuelPumpReadingsController::class, 'destroy'])->middleware('auth');
Route::post('/sales_checkout', [SalesController::class, 'checkout'])->middleware('auth');
Route::get('/sales_checkout/{id}', [SalesController::class, 'checkOutForm'])->middleware('auth');
Route::post('/sales_confirm', [SalesController::class, 'confirmSale'])->middleware('auth');
Route::get('/sale_item/remove/{id}', [SalesController::class, 'removeSalesItem'])->middleware('auth');
Route::get('/delete_sales/{id}', [SalesController::class, 'destroy'])->middleware('auth');
Route::get('/unauthorized', [HomeController::class, 'showNoPermissionPage'])->middleware('auth');
Route::resource('roles', RoleController::class)->middleware('auth');
Route::resource('users', UserController::class)->middleware('auth');
Route::resource('debt_payments', DebtPaymentsController::class)->middleware('auth');
Route::resource('expenses', ExpensesController::class)->middleware('auth');
Route::get('/debts_by_customers', [App\Http\Controllers\DebtsController::class, 'debtsByCustomers'])->middleware('auth');

app/Models/Stock.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\HasMedia;
use Illuminate\Database\Eloquent\Model;

class Stock extends Model implements HasMedia
{
    use HasFactory,InteractsWithMedia;

    protected $fillable = [
        'product_id',
        'suppliers_name',
        'no_of_items_bought',
        'total_amount',
        'unit_buying_price',
        'unit_selling_price',
        'added_by'
    ];

    public function product()
    {
        return $this->belongsTo(Product::class,'product_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'added_by');
    }
}

app/Http/Controllers/StocksController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Stock;
use App\Models\Product;
use App\Models\ItemSale;
use Auth;

class StocksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    function __construct()
    {
         $this->middleware('permission:can-view-stocks|can-create-stock|can-edit-stock|can-delete-stock', ['only' => ['index','store']]);
         $this->middleware('permission:can-create-stock', ['only' => ['create','store']]);
         $this->middleware('permission:can-edit-stock', ['only' => ['edit','update']]);
         $this->middleware('permission:can-delete-stock', ['only' => ['destroy']]);
    }


    public function index()
    {
        $stocks = Stock::all()->sortByDesc("created_at");

        return view('stocks.all_stocks', compact('stocks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $products = Product::all();

        return view('stocks.add_stock', compact('products'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $valiator = $request->validate([
            'product_id' => 'required|integer',
            'no_of_items_bought' => 'required',
            'total_amount' => 'required',
            'unit_buying_price' => 'required',
            'unit_selling_price' => 'required',
        ]);
        //save the stocks in stocks
        $request['added_by'] = Auth::user()->id;
        $stock = Stock::create($request->all());
        //save the receipt
        if($request->hasFile('picture') && $request->file('picture')->isValid()){
            $stock->addMediaFromRequest('picture')->toMediaCollection('stock_receipts');
        }
        //update product
        $product = $stock->product;
        $product->unit_buying_price = $request->unit_buying_price;
        $product->unit_selling_price = $request->unit_selling_price;
        $product->in_stock +=$request->no_of_items_bought;
        $product->save();

        return redirect('/stocks');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $stock = Stock::findOrFail($id);

        $stock_image =$stock->getFirstMediaURL('stock_receipts');
        return view('stocks.stock_details',compact('stock','stock_image'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $stock = Stock::findOrFail($id);
        return view('stocks.edit_stock', compact('stock'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $stock = Stock::findOrFail($id);
        //update stock
        $valiator = $request->validate([
            'product_id' => 'required|integer',
            'no_of_items_bought' => 'required',
            'total_amount' => 'required',
            'unit_buying_price' => 'required',
            'unit_selling_price' => 'required',
        ]);
        //save the stocks in stocks
        $stock->update($request->all());
        //save the receipt
        if($request->hasFile('picture') && $request->file('picture')->isValid()){
            $stock->clearMediaCollection('stock_receipts');
            $stock->addMediaFromRequest('picture')->toMediaCollection('stock_receipts');
        }

        //fetch sales for the product
        $sold_items = 0;
        $sales = ItemSale::where('product_id', $request->product_id)->get();
        //check if there are sales
        if ($sales->count() > 0) {
            $sold_items = $sales->sum('no_of_items');
        }

        //calculate all stock items
        $stock_count = 0;
        $stocks_available = Stock::where('product_id',$request->product_id)->get();
        if ($stocks_available->count() >0) {
            $stock_count = $stocks_available->sum('no_of_items_bought');
        }
        //update product
        $product = $stock->product;
        $product->unit_buying_price = $request->unit_buying_price;
        $product->unit_selling_price = $request->unit_selling_price;
        $product->in_stock = $stock_count - $sold_items;
        $product->save();

        return redirect('/stocks/'.$stock->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $stock = Stock::findOrFail($id);
        $stock->delete();
        //check if there is a receipt
        $stock_image = $stock->getFirstMediaURL('stock_receipts');
        if ($stock_image !='') {
            $stock->clearMediaCollection('stock_receipts');
        }

        //fetch sales for the product
        $sold_items = 0;
        $sales = ItemSale::where('product_id', $stock->product_id)->get();
        //check if there are sales
        if ($sales->count() > 0) {
            $sold_items = $sales->sum('no_of_items');
        }

        //calculate all stock items
        $stock_count = 0;
        $stocks_available = Stock::where('product_id',$stock->product_id)->get();
        if ($stocks_available->count() >0) {
            $stock_count = $stocks_available->sum('no_of_items_bought');
        }
        //update product
        $product = $stock->product;
        $product->in_stock = $stock_count - $sold_items;
        $product->save();



        return redirect('/stocks');
    }
}

resources/views/stocks/add_stock.blade.php
@extends('layouts.master')
@section('main-content')
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Add a New Stock</h2>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            @if ($errors->any())
                @foreach ($errors->all() as $error)
                    <div class="text-center text-danger">{{$error}}</div>
                @endforeach
            @endif
            <div class="col-sm-12 col-md-12">
                <div class="col-md-8 col-sm-8">
                    <form id="demo-form2" class="form-horizontal form-label-left" action="/stocks" method="post" enctype="multipart/form-data" autocomplete="off">
                        @csrf
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="product_id">Product <span class="required">*</span>
                          </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            <select class="form-control" id="product_id" name="product_id" required>
                                <option value="">Choose option</option>
                                @foreach ($products as $product)
                                <option value="{{$product->id}}">{{$product->name}}</option>
                                @endforeach
                              </select>
                          </div>
                        </div>
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="suppliers_name">Supplier <span class="required">*</span>
                          </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" name="suppliers_name"  id="suppliers_name"  class="form-control col-md-7 col-xs-12">
                          </div>
                        </div>
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="no_of_items_bought">No of Items <span class="required">*</span>
                          </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="number" name="no_of_items_bought"  id="no_of_items_bought"  class="form-control col-md-7 col-xs-12" required>
                          </div>
                        </div>
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="total_amount">Total Amount <span class="required">*</span>
                          </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="number" name="total_amount"  id="total_amount" required="required" class="form-control col-md-7 col-xs-12">
                          </div>
                        </div>
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="unit_buying_price">Unit Buying Price <span class="required">*</span>
                          </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" name="unit_buying_price"  id="unit_buying_price" required="required" class="form-control col-md-7 col-xs-12" readonly step="0.01">
                          </div>
                        </div>
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="unit_selling_price">Unit Selling Price <span class="required">*</span>
                          </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="number" name="unit_selling_price"  id="unit_selling_price" required="required" class="form-control col-md-7 col-xs-12" step="0.01">
                          </div>
                        </div>
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Receipt </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="file" data-role="magic-overlay" data-target="#pictureBtn" data-edit="insertImage" name="picture">
                          </div>
                        </div>
                        <div class="form-group">
                          <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button type="submit" class="btn btn-success">Submit</button>
                          </div>
                        </div>

                      </form>
                </div>
                <div class="col-md-4 col-sm-4">
                    <img src="" alt="" id="product_image" style=" max-height:100%; max-width:100%;">
                    <h5 class="price" id="in_stock"></h5>
                </div>
            </div>
          </div>
        </div>
      </div>
</div>
@endsection

@section('custom-scripts')
    {{-- custom jquery --}}
    <script>
 $(document).ready(function(){
            //retrive the product and check if there is an image when making a sale
            $('#product_id').on('change', function(){
                $.get('/api/product/'+$( "#product_id").val()+'/image_url',  // url
                    function (data, textStatus, jqXHR) {
                        //fill unit buying price
                        $('#unit_buying_price').val(data.unit_buying_price);
                        $('#unit_selling_price').val(data.unit_selling_price);
                        if (data.image_url !='') {
                            $("#product_image").attr("src",data.image_url);
                        }else{
                            $("#product_image").attr("src",'/admin/images/no-image.png');
                        }

                        //show amount in stock
                        $('#in_stock').html(data.in_stock+' In Stock');
                });
            })
            //update the current unit buying price
            $('#total_amount').on('blur', function(){
                let total_amount = parseFloat($('#total_amount').val());
                let no_of_items = parseFloat($('#no_of_items_bought').val());
                $('#unit_buying_price').val(parseFloat(total_amount/no_of_items));
            })
        });
     </script>
@endsection

resources/views/stocks/all_stocks.blade.php
@extends('layouts.master')
@section('main-content')
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Stock List</h2>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <p class="text-muted font-13 m-b-30">
              List of stock added
            </p>

            <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%" height="100%">
              <thead>
                <tr>
                  <th class="text-center">S/N</th>
                  <th>Product Name</th>
                  <th>Supplier</th>
                  <th>Unit Buying Price</th>
                  <th>Unit Selling Price</th>
                  <th>No of Items</th>
                  <th>Amount</th>
                  <th>Added On</th>
                  <th>Added By</th>
                  <th>Manage</th>
                </tr>
              </thead>
              <tbody>
                  @foreach ($stocks as $stock)
                  <tr>
                    <td class="text-center">{{$loop->index + 1}}</td>
                    <td>{{$stock->product->name}}</td>
                    <td>{{$stock->suppliers_name}}</td>
                    <td>{{$stock->unit_buying_price}}</td>
                    <td>{{$stock->unit_selling_price}}</td>
                    <td>{{$stock->no_of_items_bought}}</td>
                    <td>{{$stock->total_amount}}</td>
                    <td>{{$stock->created_at}}</td>
                    @if ($stock->user != '')
                    <td>{{$stock->user->name}}</td>
                    @else
                    <td>UNKNOWN</td>
                    @endif
                    <td>
                        <a class="btn btn-sm btn-info" href="stocks/{{$stock->id}}">Manage</a>
                    </td>
                  </tr>
                  @endforeach
              </tbody>
            </table>


          </div>
        </div>
      </div>
</div>
@endsection

resources/views/stocks/edit_stock.blade.php
@extends('layouts.master')
@section('main-content')
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Edit Stock</h2>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            @if ($errors->any())
                @foreach ($errors->all() as $error)
                    <div class="text-center text-danger">{{$error}}</div>
                @endforeach
            @endif
            <div class="col-sm-12 col-md-12">
                <div class="col-md-8 col-sm-8">
                    <form id="demo-form2" class="form-horizontal form-label-left" action="/stocks/{{$stock->id}}" method="post" enctype="multipart/form-data" autocomplete="off">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="product_id">Product <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                              <input type="text" name="name"   class="form-control col-md-7 col-xs-12" value="{{$stock->product->name}}" readonly>
                              <input type="hidden" name="product_id" id="product" class="form-control col-md-7 col-xs-12" value="{{$stock->product->id}}">
                            </div>
                          </div>
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="suppliers_name">Supplier <span class="required">*</span>
                          </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" name="suppliers_name"  id="suppliers_name"  class="form-control col-md-7 col-xs-12" value="{{$stock->suppliers_name}}">
                          </div>
                        </div>
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="no_of_items_bought">No of Items <span class="required">*</span>
                          </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="number" name="no_of_items_bought"  id="no_of_items_bought"  class="form-control col-md-7 col-xs-12" required value="{{$stock->no_of_items_bought}}">
                          </div>
                        </div>
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="total_amount">Total Amount <span class="required">*</span>
                          </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="number" name="total_amount"  id="total_amount" required="required" class="form-control col-md-7 col-xs-12" value="{{$stock->total_amount}}">
                          </div>
                        </div>
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="unit_buying_price">Unit Buying Price <span class="required">*</span>
                          </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="text" name="unit_buying_price"  id="unit_buying_price" required="required" class="form-control col-md-7 col-xs-12" readonly step="0.01" value="{{$stock->unit_buying_price}}">
                          </div>
                        </div>
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="unit_selling_price">Unit Selling Price <span class="required">*</span>
                          </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="number" name="unit_selling_price"  id="unit_selling_price" required="required" class="form-control col-md-7 col-xs-12" step="0.01" value="{{$stock->unit_selling_price}}">
                          </div>
                        </div>
                        <div class="form-group">
                          <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Receipt </label>
                          <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="file" data-role="magic-overlay" data-target="#pictureBtn" data-edit="insertImage" name="picture">
                          </div>
                        </div>
                        <div class="form-group">
                          <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button type="submit" class="btn btn-success">Submit</button>
                          </div>
                        </div>

                      </form>
                </div>
                <div class="col-md-4 col-sm-4">
                    <img src="" alt="" id="product_image" style=" max-height:100%; max-width:100%;">
                    <h5 class="price" id="in_stock"></h5>
                </div>
            </div>
          </div>
        </div>
      </div>
</div>
@endsection

@section('custom-scripts')
    {{-- custom jquery --}}
    <script>
 $(document).ready(function(){
            //retrive the product and check if there is an image when making a sale
                $.get('/api/product/'+$( "#product").val()+'/image_url',  // url
                    function (data, textStatus, jqXHR) {
                        //fill unit buying price
                        $('#unit_buying_price').val(data.unit_buying_price);
                        $('#unit_selling_price').val(data.unit_selling_price);
                        if (data.image_url !='') {
                            $("#product_image").attr("src",data.image_url);
                        }else{
                            $("#product_image").attr("src",'/admin/images/no-image.png');
                        }

                        //show amount in stock
                        $('#in_stock').html(data.in_stock+' In Stock');
                });
            //update the current unit buying price
            $('#total_amount').on('blur', function(){
                let total_amount = parseFloat($('#total_amount').val());
                let no_of_items = parseFloat($('#no_of_items_bought').val());
                $('#unit_buying_price').val(parseFloat(total_amount/no_of_items));
            })
        });
     </script>
@endsection

resources/views/stocks/stock_details.blade.php
@extends('layouts.master')
@section('main-content')
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Stock Details</h2>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">

            <div class="col-md-7 col-sm-7 col-xs-12">
              <div class="product-image">
                  @if ($stock_image != '')
                    <img src="{{$stock_image }}" alt="...">
                  @else
                  <img src="/admin/images/no-image.png" alt="..." width="100" height="400">
                  @endif
              </div>
            </div>

            <div class="col-md-5 col-sm-5 col-xs-12" style="border:0px solid #e5e5e5;">

              <h3 class="prod_title">{{$stock->product->name}}</h3>

              <p> No of items Bought: {{$stock->no_of_items_bought}}</p>
              <h1 class="price"> KES {{$stock->total_amount}}</h1>
              <p> Unit Buying Price: {{$stock->unit_buying_price}}</p>
              <p> Unit selling Price: {{$stock->unit_selling_price}}</p>
              <br>
              <div class="">

                <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
                    <div class="modal-dialog modal-sm">
                      <div class="modal-content">
                          <form action="" method="post" action="{{route('stocks.destroy',$stock->id)}}">
                            @csrf
                            @method('delete')
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
                          </button>
                          <h4 class="modal-title" id="myModalLabel2">Delete the stock of {{$stock->product->name}}?</h4>
                        </div>
                        <div class="modal-body">
                          <p>Are you sure you want to delete  this stock of {{$stock->product->name}}?</p>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                          <button type="submit" class="btn btn-primary" >Yes Delete</button>
                        </div>
                    </form>
                      </div>
                    </div>
                  </div>
                <a  href="{{route('stocks.edit',$stock->id)}}"  type="button" class="btn btn-warning">Edit</a>
                <button type="button" class="btn btn-danger" data-toggle="modal" data-target=".bs-example-modal-sm">Delete</button>
              </div>
            </div>
          </div>
        </div>
      </div>
</div>
@endsection