routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductsController;
use App\Http\Controllers\StocksController;
use App\Http\Controllers\SalesController;
use App\Http\Controllers\FuelPumpsController;
use App\Http\Controllers\FuelPumpReadingsController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CustomersController;
use App\Http\Controllers\DebtsController;
use App\Http\Controllers\DebtPaymentsController;
use App\Http\Controllers\ExpensesController;
use App\Models\Sale;
use App\Models\Stock;
use App\Models\Product;
use App\Models\FuelPump;
use App\Models\User;
use App\Models\FuelPumpReading;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/business_performance', [App\Http\Controllers\HomeController::class, 'businessPerfomance']);
Route::get('/products_performance', [App\Http\Controllers\HomeController::class, 'productsPerfomance']);
Route::resource('products', ProductsController::class)->middleware('auth');
Route::resource('customers', CustomersController::class)->middleware('auth');
Route::resource('debts', DebtsController::class)->middleware('auth');
Route::resource('stocks', StocksController::class)->middleware('auth');
Route::resource('sales', SalesController::class)->middleware('auth');
Route::resource('fuel_pumps', FuelPumpsController::class)->middleware('auth');
Route::get('fuel_pump/{pump_id}/calibrate', [App\Http\Controllers\FuelPumpsController::class, 'calibratePump'])->middleware('auth');
Route::post('fuel_pump/{pump_id}/calibrate', [App\Http\Controllers\FuelPumpsController::class, 'calibratePumpUpdate'])->middleware('auth');
Route::resource('fuel_pumps_readings', FuelPumpReadingsController::class)->middleware('auth');
Route::get('fuel_pumps_reading/{reading_id}/delete', [App\Http\Controllers\FuelPumpReadingsController::class, 'destroy'])->middleware('auth');
Route::post('/sales_checkout', [SalesController::class, 'checkout'])->middleware('auth');
Route::get('/sales_checkout/{id}', [SalesController::class, 'checkOutForm'])->middleware('auth');
Route::post('/sales_confirm', [SalesController::class, 'confirmSale'])->middleware('auth');
Route::get('/sale_item/remove/{id}', [SalesController::class, 'removeSalesItem'])->middleware('auth');
Route::get('/delete_sales/{id}', [SalesController::class, 'destroy'])->middleware('auth');
Route::get('/unauthorized', [HomeController::class, 'showNoPermissionPage'])->middleware('auth');
Route::resource('roles', RoleController::class)->middleware('auth');
Route::resource('users', UserController::class)->middleware('auth');
Route::resource('debt_payments', DebtPaymentsController::class)->middleware('auth');
Route::resource('expenses', ExpensesController::class)->middleware('auth');
Route::get('/debts_by_customers', [App\Http\Controllers\DebtsController::class, 'debtsByCustomers'])->middleware('auth');

app/Models/Debt.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Debt extends Model
{
    use HasFactory;

    protected $fillable = [
        'description','added_by','debt_amount', 'customer_id'
    ];
    public function user()
    {
        return $this->belongsTo(User::class, 'added_by');
    }
    public function customer()
    {
        return $this->belongsTo(Customer::class, 'customer_id');
    }
}

app/Http/Controllers/DebtsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Debt;
use App\Models\Customer;
use Auth;

class DebtsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
   

    public function index(Request $request)
    {
        //check if there is a customer_id on the request
        if ($request->customer_id) {
            //get the debts only for this customer
            $debt_title = Customer::find($request->customer_id)->name;

            $debts = Debt::where('customer_id', $request->customer_id)->get()->sortByDesc("created_at");
            
        }
        else{
            //return all debts
            $debt_title = "All Customers";
            $debts = Debt::all()->sortByDesc("created_at");
        }
        $debt_amount = $debts->sum('debt_amount');

        return view('debts/all_debts',compact('debts', 'debt_title', 'debt_amount'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $customers = Customer::all();
        return view('debts/create_debt', compact('customers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $valiator = $request->validate([
            'debt_amount' => 'required',
            'customer_id' => 'required'
        ]);

        $request['added_by'] = Auth::user()->id;
        $debt = Debt::create($request->all());

        //update the customer
        $customer = Customer::find($request->customer_id);
        $customer->debt_amount += $request->debt_amount;
        $customer->save();
        return redirect('/debts');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $debt = Debt::findOrFail($id);

        return view('debts.debt_details', compact('debt'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $debt = Debt::findOrFail($id);
        $customers = Customer::all();
        return view('debts.edit_debt',compact('debt', 'customers'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // $valiator = $request->validate([
        //     'debt_amount' => 'required',
        // ]);
        // $debt = Debt::findOrFail($id);
        // $request['customer_id'] = $debt->customer_id;
        // $debt ->update($request->all());

        // return redirect('/debts/'.$debt->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $debt = Debt::findOrFail($id);
        
        $debt->delete();
         //update the customer
         $customer = Customer::find($debt->customer_id);
         $customer->debt_amount -= $debt->debt_amount;
         $customer->save();
         
        return redirect('/debts');
    }

    public function debtsByCustomers()
    {
       $customers = Customer::where('debt_amount', '>', '0')->get()->sortByDesc("debt_amount");

       return view('debts.customers',compact('customers'));
    }

}

resources/views/debts/all_debts.blade.php
@extends('layouts.master')
@section('main-content')
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <div class="row">
              <div class="col-md-10">
                <h2>Debts List History For {{$debt_title}}</h2>
              </div>
              <div class="col-md-2">
                <a class="btn btn-success float-right" href="{{ route('debts.create') }}"> Add Debt</a>
              </div>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <p class="text-muted font-13 m-b-30">
              List of debts history for {{$debt_title}} available in the database
            </p>

            <h5 class="text-success">Total Debt for {{$debt_title}} is KES: {{$debt_amount}}</h5>

            <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%" height="100%">
              <thead>
                <tr>
                  <th class="text-center">S/N</th>
                  <th>Customer Name</th>
                  <th>Phone Number</th>
                  <th>Description</th>
                  <th>Debt Amount</th>
                  <th>Added On</th>
                  <th>Added By</th>
                  <th>Manage</th>
                </tr>
              </thead>
              <tbody>
                  @foreach ($debts as $debt)
                  <tr>
                    <td class="text-center">{{$loop->index + 1}}</td>
                    <td>{{$debt->customer->name}}</td>
                    <td>{{$debt->customer->phone_number}}</td>
                    <td>{{$debt->description}}</td>
                    <td>{{$debt->debt_amount}}</td>
                    <td>{{$debt->created_at}}</td>
                    @if ($debt->user != '')
                    <td>{{$debt->user->name}}</td>
                    @else
                    <td>UNKNOWN</td>
                    @endif
                    <td>
                        <a class="btn btn-sm btn-info" href="debts/{{$debt->id}}">Manage</a>
                    </td>
                  </tr>
                  @endforeach
              </tbody>
            </table>


          </div>
        </div>
      </div>
</div>
@endsection

resources/views/debts/create_debt.blade.php
@extends('layouts.master')
@section('main-content')
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Add a New Debt</h2>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            @if ($errors->any())
                @foreach ($errors->all() as $error)
                    <div class="text-center text-danger">{{$error}}</div>
                @endforeach
            @endif
            <form id="demo-form2" class="form-horizontal form-label-left"  action="/debts" method="post" enctype="multipart/form-data" autocomplete="off">
                @csrf
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="customer_id">Customer Name <span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <select class="form-control" id="product_id" name="customer_id" required>
                        <option value="">Choose customer</option>
                        @foreach ($customers as $customer)
                        <option value="{{$customer->id}}">{{$customer->name}}</option>
                        @endforeach
                      </select>
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="description">Description 
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <textarea id="description" name="description"  class="form-control"  data-parsley-trigger="keyup" data-parsley-minlength="20" data-parsley-maxlength="100" data-parsley-minlength-message="Come on! You need to enter at least a 20 caracters long comment.." data-parsley-validation-threshold="10"></textarea>
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="debt_amount">Debt Amount <span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="number" name="debt_amount"  id="debt_amount" required="required" class="form-control col-md-7 col-xs-12"  required step="0.01">
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                    <button type="submit" class="btn btn-success">Submit</button>
                  </div>
                </div>

              </form>


          </div>
        </div>
      </div>
</div>
@endsection

resources/views/debts/customers.blade.php
@extends('layouts.master')
@section('main-content')
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <div class="row">
              <div class="col-md-10">
                <h2>Debts Customer List</h2>
              </div>
              <div class="col-md-2">
                <a class="btn btn-success float-right" href="{{ route('debts.create') }}"> Add Debt</a>
              </div>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <p class="text-muted font-13 m-b-30">
              List of customers available in the database with their debts
            </p>
            <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%" height="100%">
              <thead>
                <tr>
                  <th class="text-center">S/N</th>
                  <th>Name</th>
                  <th>Phone Number</th>
                  <th>Description</th>
                  <th>Debt Amount</th>
                  <th>Added On</th>
                  <th>Added By</th>
                  <th>Manage</th>
                </tr>
              </thead>
              <tbody>
                  @foreach ($customers as $customer)
                  <tr>
                    <td class="text-center">{{$loop->index + 1}}</td>
                    <td>{{$customer->name}}</td>
                    <td>{{$customer->phone_number}}</td>
                    <td>{{$customer->description}}</td>
                    <td>{{$customer->debt_amount}}</td>
                    <td>{{$customer->created_at}}</td>
                    @if ($customer->user != '')
                    <td>{{$customer->user->name}}</td>
                    @else
                    <td>UNKNOWN</td>
                    @endif
                    <td>
                        <a class="btn btn-sm btn-info" href="debts?customer_id={{$customer->id}}">Debts History</a>
                        <a class="btn btn-sm btn-success" href="debt_payments?customer_id={{$customer->id}}">Payment History</a></td>
                  </tr>
                  @endforeach
              </tbody>
            </table>
          </div>
        </div>
      </div>
</div>
@endsection

resources/views/debts/debt_details.blade.php
@extends('layouts.master')
@section('main-content')
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Debt Details</h2>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <div class="col-md-12 col-sm-12 col-xs-12" style="border:0px solid #e5e5e5;">

              <h3 class="prod_title" >Customer Name: {{$debt->customer->name}}</h3>

              <p>Description: {{$debt->description}}</p>
              <h2>Debt Amount: {{$debt->debt_amount}}</h2>
              <br>
                <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
                    <div class="modal-dialog modal-sm">
                      <div class="modal-content">
                          <form action="" method="post" action="{{route('debts.destroy',$debt->id)}}">
                            @csrf
                            @method('delete')
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
                          </button>
                          <h4 class="modal-title" id="myModalLabel2">Delete {{$debt->name}}</h4>
                        </div>
                        <div class="modal-body">
                          <p>Are you sure you want to delete {{$debt->name}}? Remember that you will lose all the information for this debt including the debt</p>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                          <button type="submit" class="btn btn-primary" >Yes Delete</button>
                        </div>
                    </form>
                      </div>
                    </div>
                  </div>
                {{-- <a type="button" class="btn btn-warning" href="/debts/{{$debt->id}}/edit">Edit</a> --}}
                <button type="button" class="btn btn-danger" data-toggle="modal" data-target=".bs-example-modal-sm">Delete</button>
              </div>
            </div>
          </div>
        </div>
      </div>
</div>
@endsection

resources/views/debts/edit_debt.blade.php
@extends('layouts.master')
@section('main-content')
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Edit debt</h2>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            @if ($errors->any())
                @foreach ($errors->all() as $error)
                    <div class="text-center text-danger">{{$error}}</div>
                @endforeach
            @endif
            <form id="demo-form2"  class="form-horizontal form-label-left"  action="/debts/{{$debt->id}}" method="post" enctype="multipart/form-data" autocomplete="off">
                @csrf
                @method('PUT')
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="debt_name">Customer Name <span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="text" name="customer_id"  id="debt_name" required="required" class="form-control col-md-7 col-xs-12" value="{{$debt->customer->name}}" readonly>
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="description">Description <span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <textarea id="description" name="description"  class="form-control" >{{$debt->description}}</textarea>
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="debt_amount">Debt Amount <span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="text" name="debt_amount"  id="debt_amount" required="required" class="form-control col-md-7 col-xs-12" value="{{$debt->debt_amount}}">
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                    <button type="submit" class="btn btn-success">Submit</button>
                  </div>
                </div>

              </form>


          </div>
        </div>
      </div>
</div>
@endsection