routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductsController;
use App\Http\Controllers\StocksController;
use App\Http\Controllers\SalesController;
use App\Http\Controllers\FuelPumpsController;
use App\Http\Controllers\FuelPumpReadingsController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CustomersController;
use App\Http\Controllers\DebtsController;
use App\Http\Controllers\DebtPaymentsController;
use App\Http\Controllers\ExpensesController;
use App\Models\Sale;
use App\Models\Stock;
use App\Models\Product;
use App\Models\FuelPump;
use App\Models\User;
use App\Models\FuelPumpReading;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/business_performance', [App\Http\Controllers\HomeController::class, 'businessPerfomance']);
Route::get('/products_performance', [App\Http\Controllers\HomeController::class, 'productsPerfomance']);
Route::resource('products', ProductsController::class)->middleware('auth');
Route::resource('customers', CustomersController::class)->middleware('auth');
Route::resource('debts', DebtsController::class)->middleware('auth');
Route::resource('stocks', StocksController::class)->middleware('auth');
Route::resource('sales', SalesController::class)->middleware('auth');
Route::resource('fuel_pumps', FuelPumpsController::class)->middleware('auth');
Route::get('fuel_pump/{pump_id}/calibrate', [App\Http\Controllers\FuelPumpsController::class, 'calibratePump'])->middleware('auth');
Route::post('fuel_pump/{pump_id}/calibrate', [App\Http\Controllers\FuelPumpsController::class, 'calibratePumpUpdate'])->middleware('auth');
Route::resource('fuel_pumps_readings', FuelPumpReadingsController::class)->middleware('auth');
Route::get('fuel_pumps_reading/{reading_id}/delete', [App\Http\Controllers\FuelPumpReadingsController::class, 'destroy'])->middleware('auth');
Route::post('/sales_checkout', [SalesController::class, 'checkout'])->middleware('auth');
Route::get('/sales_checkout/{id}', [SalesController::class, 'checkOutForm'])->middleware('auth');
Route::post('/sales_confirm', [SalesController::class, 'confirmSale'])->middleware('auth');
Route::get('/sale_item/remove/{id}', [SalesController::class, 'removeSalesItem'])->middleware('auth');
Route::get('/delete_sales/{id}', [SalesController::class, 'destroy'])->middleware('auth');
Route::get('/unauthorized', [HomeController::class, 'showNoPermissionPage'])->middleware('auth');
Route::resource('roles', RoleController::class)->middleware('auth');
Route::resource('users', UserController::class)->middleware('auth');
Route::resource('debt_payments', DebtPaymentsController::class)->middleware('auth');
Route::resource('expenses', ExpensesController::class)->middleware('auth');
Route::get('/debts_by_customers', [App\Http\Controllers\DebtsController::class, 'debtsByCustomers'])->middleware('auth');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\HasMedia;
use Illuminate\Database\Eloquent\Model;

class Product extends Model implements HasMedia
{
    use HasFactory,InteractsWithMedia;

    protected $fillable = [
        'name',
        'description',
        'unit_selling_price',
        'in_stock',
        'added_by'
    ];

    public function stocks()
    {
        return $this->hasMany(Stock::class,'product_id');
    }
    public function itemsales()
    {
        return $this->hasMany(ItemSale::class,'product_id');
    }

    //for fuel pumps
    public function fuelpumps()
    {
        return $this->hasMany(FuelPump::class,'product_id');
    }
    //for fuel pumps
    public function fuelpumpsreadings()
    {
        return $this->hasMany(FuelPumpReading::class,'product_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'added_by');
    }
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Product;
use Auth;

class ProductsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
         $this->middleware('permission:can-view-products|can-create-products|can-edit-product|can-delete-product', ['only' => ['index','store']]);
         $this->middleware('permission:can-create-products', ['only' => ['create','store']]);
         $this->middleware('permission:can-edit-product', ['only' => ['edit','update']]);
         $this->middleware('permission:can-delete-product', ['only' => ['destroy']]);
    }

    public function index()
    {
        //return all products
        $products = Product::all()->sortByDesc("created_at");

        return view('products/all_products',compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products/create_product');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $valiator = $request->validate([
            'name' => 'required',
        ]);

        $request['added_by'] = Auth::user()->id;
        $product = Product::create($request->all());

        if($request->hasFile('picture') && $request->file('picture')->isValid()){
            $product->addMediaFromRequest('picture')->toMediaCollection('products_images');
        }

        return redirect('/products');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::findOrFail($id);

        $product_image =$product->getFirstMediaURL('products_images');
        return view('products.product_details', compact('product','product_image'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::findOrFail($id);
        return view('products.edit_product',compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $valiator = $request->validate([
            'name' => 'required',
            'unit_selling_price' => 'required',
        ]);
        $product = Product::findOrFail($id);
        $product ->update($request->all());

        if($request->hasFile('picture') && $request->file('picture')->isValid()){
            //clear existing media
            $product->clearMediaCollection('products_images');
            $product->addMediaFromRequest('picture')->toMediaCollection('products_images');
        }

        return redirect('/products/'.$product->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::findOrFail($id);
        //check if there is an upload and delete it
        if ($product->getFirstMediaURL('products_images') !='') {
            $product->clearMediaCollection('products_images');
        }
        $product->delete();
        return redirect('/products');
    }

    public function AjaxfetchProductImageUrl($product_id)
    {
        $product= Product::findOrFail($product_id);
        $product['image_url'] = $product->getFirstMediaURL('products_images');
        return response()->json($product, 200, []);
    }

}

resources/views/products/all_products.blade.php
@extends('layouts.master')
@section('main-content')
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Products List</h2>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <p class="text-muted font-13 m-b-30">
              List of products available in the database
            </p>

            <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%" height="100%">
              <thead>
                <tr>
                  <th class="text-center">S/N</th>
                  <th>Code</th>
                  <th>Name</th>
                  <th>Description</th>
                  <th>Unit Buying Price</th>
                  <th>Unit Selling Price</th>
                  <th>Items In Stock</th>
                  <th>Added On</th>
                  <th>Added By</th>
                  <th>Manage</th>
                </tr>
              </thead>
              <tbody>
                  @foreach ($products as $product)
                  <tr>
                    <td class="text-center">{{$loop->index + 1}}</td>
                    <td>{{$product->id}}</td>
                    <td>{{$product->name}}</td>
                    <td>{{$product->description}}</td>
                    <td>{{$product->unit_buying_price}}</td>
                    <td>{{$product->unit_selling_price}}</td>
                    <td>{{$product->in_stock}}</td>
                    <td>{{$product->created_at}}</td>
                    @if ($product->user != '')
                    <td>{{$product->user->name}}</td>
                    @else
                    <td>UNKNOWN</td>
                    @endif
                    <td>
                        <a class="btn btn-sm btn-info" href="products/{{$product->id}}">Manage</a>
                    </td>
                  </tr>
                  @endforeach
              </tbody>
            </table>


          </div>
        </div>
      </div>
</div>
@endsection

resources/views/products/create_product.blade.php
@extends('layouts.master')
@section('main-content')
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Add a New Product</h2>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            @if ($errors->any())
                @foreach ($errors->all() as $error)
                    <div class="text-center text-danger">{{$error}}</div>
                @endforeach
            @endif
            <form id="demo-form2" class="form-horizontal form-label-left"  action="/products" method="post" enctype="multipart/form-data" autocomplete="off">
                @csrf
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="product_name">Name <span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="text" name="name"  id="product_name" required="required" class="form-control col-md-7 col-xs-12">
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="description">Description 
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <textarea id="description" name="description"  class="form-control"  data-parsley-trigger="keyup" data-parsley-minlength="20" data-parsley-maxlength="100" data-parsley-minlength-message="Come on! You need to enter at least a 20 caracters long comment.." data-parsley-validation-threshold="10"></textarea>
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Picture</label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="file" data-role="magic-overlay" data-target="#pictureBtn" data-edit="insertImage" name="picture">
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                    <button type="submit" class="btn btn-success">Submit</button>
                  </div>
                </div>

              </form>


          </div>
        </div>
      </div>
</div>
@endsection

resources/views/products/edit_product.blade.php
@extends('layouts.master')
@section('main-content')
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Edit Product</h2>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            @if ($errors->any())
                @foreach ($errors->all() as $error)
                    <div class="text-center text-danger">{{$error}}</div>
                @endforeach
            @endif
            <form id="demo-form2"  class="form-horizontal form-label-left"  action="/products/{{$product->id}}" method="post" enctype="multipart/form-data" autocomplete="off">
                @csrf
                @method('PUT')
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="product_name">Name <span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="text" name="name"  id="product_name" required="required" class="form-control col-md-7 col-xs-12" value="{{$product->name}}">
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="unit_selling_price">Unit Selling Price <span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="number" name="unit_selling_price"  id="unit_selling_price" required="required" class="form-control col-md-7 col-xs-12" value="{{$product->unit_selling_price}}" required step="0.01">
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="in_stock">Items In Stock <span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="number" name="in_stock"  id="in_stock" required="required" class="form-control col-md-7 col-xs-12" value="{{$product->in_stock}}" required step="0.01">
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="description">Description <span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <textarea id="description" name="description"  class="form-control" >{{$product->description}}</textarea>
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Picture</label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="file" data-role="magic-overlay" data-target="#pictureBtn" data-edit="insertImage" name="picture">
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                    <button type="submit" class="btn btn-success">Submit</button>
                  </div>
                </div>

              </form>


          </div>
        </div>
      </div>
</div>
@endsection

resources/views/products/product_details.blade.php
@extends('layouts.master')
@section('main-content')
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Product Details</h2>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">

            <div class="col-md-7 col-sm-7 col-xs-12">
              <div class="product-image">
                  @if ($product_image != '')
                    <img src="{{$product_image}}" alt="...">
                  @else
                  <img src="/admin/images/no-image.png" alt="..." width="100" height="400">
                  @endif
              </div>
            </div>

            <div class="col-md-5 col-sm-5 col-xs-12" style="border:0px solid #e5e5e5;">

              <h3 class="prod_title">{{$product->name}}</h3>

              <p>{{$product->description}}</p>
              <br>
              <h2> No of Items In Stock: {{$product->in_stock}}</h2>
              <h2> Product Code: {{$product->id}}</h2>
              <h2 class="price"> Unit selling Price: <span class="price"> KES {{$product->unit_selling_price}}</span></h2>
              <div class="">

                <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
                    <div class="modal-dialog modal-sm">
                      <div class="modal-content">
                          <form action="" method="post" action="{{route('products.destroy',$product->id)}}">
                            @csrf
                            @method('delete')
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
                          </button>
                          <h4 class="modal-title" id="myModalLabel2">Delete {{$product->name}}</h4>
                        </div>
                        <div class="modal-body">
                          <p>Are you sure you want to delete {{$product->name}}?</p>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                          <button type="submit" class="btn btn-primary" >Yes Delete</button>
                        </div>
                    </form>
                      </div>
                    </div>
                  </div>
                <a type="button" class="btn btn-warning" href="/products/{{$product->id}}/edit">Edit</a>
                <button type="button" class="btn btn-danger" data-toggle="modal" data-target=".bs-example-modal-sm">Delete</button>
              </div>
            </div>
          </div>
        </div>
      </div>
</div>
@endsection

resources/views/products/products_performance.blade.php
@extends('layouts.master')
@section('main-content')
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <div class="row">
              <form action="/products_performance" method="get">
              <div class="col-md-6">
                <h4>Products Performace List : <small>{{$dateRangeString}}</small></h4>
              </div>
              <div class="col-md-4">
                <div id="reportrange" class="pull-right" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc">
                  <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>
                  <span id="dateRange">{{$dateStringText}}</span> <b class="caret"></b>
                  <input type="hidden" id="dateRangeText" name="dateRangeText">
                  </div>
              </div>
              <div class="col-md-2">
                <button type="submit" class="btn btn-success btn-sm">Filter</button>
              </div>
            </form>
            </div>
          </div>
          <div class="x_content">
            <p class="text-muted font-13 m-b-30">
              List of products and their performances
            </p>

            <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%" height="100%">
              <thead>
                <tr>
                  <th class="text-center">S/N</th>
                  <th>Code</th>
                  <th>Name</th>
                  <th>Stock Value</th>
                  <th>Total Sales</th>
                  <th>Total Profits</th>
                  <th>Description</th>
                  <th>Unit Buying Price</th>
                  <th>Unit Selling Price</th>
                  <th>Items In Stock</th>
                  <th>Added On</th>
                  <th>Manage</th>
                </tr>
              </thead>
              <tbody>
                  @foreach ($products as $product)
                  <tr>
                    <td class="text-center">{{$loop->index + 1}}</td>
                    <td>{{$product->id}}</td>
                    <td>{{$product->name}}</td>
                    <td>{{$product->stock_value}}</td>
                    <td>{{$product->total_sales}}</td>
                    <td>{{$product->total_profit}}</td>
                    <td>{{$product->description}}</td>
                    <td>{{$product->unit_buying_price}}</td>
                    <td>{{$product->unit_selling_price}}</td>
                    <td>{{$product->in_stock}}</td>
                    <td>{{$product->created_at}}</td>
                    <td>
                        <a class="btn btn-sm btn-info" href="products/{{$product->id}}">Manage</a>
                    </td>
                  </tr>
                  @endforeach
              </tbody>
            </table>


          </div>
        </div>
      </div>
</div>
@endsection
@section('custom-scripts')
<script>
$(document).ready(function(){

    $("#dateRange").on('DOMSubtreeModified',function(){
        $('#dateRangeText').val($("#dateRange").text());
    });
});
</script>
@endsection